CREATE TABLE transaction_recurrences (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id NUMBER(19) NOT NULL,
    frequency VARCHAR2(16) NOT NULL,
    start_date DATE NOT NULL,
    next_occurrence_date DATE NOT NULL,
    end_date DATE,
    active NUMBER(1) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT pk_transaction_recurrences PRIMARY KEY (id),
    CONSTRAINT fk_transaction_recurrences_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_transaction_recurrences_user ON transaction_recurrences (user_id);
CREATE INDEX idx_transaction_recurrences_due ON transaction_recurrences (active, next_occurrence_date);

ALTER TABLE transactions ADD recurrence_id NUMBER(19);
ALTER TABLE transactions ADD CONSTRAINT fk_transactions_recurrence FOREIGN KEY (recurrence_id) REFERENCES transaction_recurrences (id);
CREATE INDEX idx_transactions_recurrence ON transactions (recurrence_id);
