CREATE TABLE transaction_attachments (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    transaction_id NUMBER(19) NOT NULL,
    original_filename VARCHAR2(255) NOT NULL,
    content_type VARCHAR2(128) NOT NULL,
    size_bytes NUMBER(19) NOT NULL,
    storage_path VARCHAR2(500) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT pk_transaction_attachments PRIMARY KEY (id),
    CONSTRAINT fk_transaction_attachments_transaction FOREIGN KEY (transaction_id) REFERENCES transactions (id)
);

CREATE INDEX idx_transaction_attachments_transaction ON transaction_attachments (transaction_id);
