CREATE TABLE pdf_imports (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id NUMBER(19) NOT NULL,
    account_id NUMBER(19) NOT NULL,
    original_filename VARCHAR2(255) NOT NULL,
    storage_path VARCHAR2(500) NOT NULL,
    status VARCHAR2(30) NOT NULL,
    failure_reason VARCHAR2(1000),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT pk_pdf_imports PRIMARY KEY (id),
    CONSTRAINT fk_pdf_imports_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_pdf_imports_account FOREIGN KEY (account_id) REFERENCES accounts (id)
);

CREATE INDEX idx_pdf_imports_user ON pdf_imports (user_id);
