CREATE TABLE pdf_import_items (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pdf_import_id NUMBER(19) NOT NULL,
    transaction_date DATE NOT NULL,
    description VARCHAR2(255) NOT NULL,
    amount NUMBER(19,2) NOT NULL,
    type VARCHAR2(16) NOT NULL,
    category_id NUMBER(19),
    status VARCHAR2(20) NOT NULL,
    transaction_id NUMBER(19),
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT pk_pdf_import_items PRIMARY KEY (id),
    CONSTRAINT fk_pdf_import_items_import FOREIGN KEY (pdf_import_id) REFERENCES pdf_imports (id),
    CONSTRAINT fk_pdf_import_items_category FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT fk_pdf_import_items_transaction FOREIGN KEY (transaction_id) REFERENCES transactions (id)
);

CREATE INDEX idx_pdf_import_items_import ON pdf_import_items (pdf_import_id);
