CREATE TABLE budgets (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id NUMBER(19) NOT NULL,
    category_id NUMBER(19) NOT NULL,
    budget_month DATE NOT NULL,
    limit_amount NUMBER(19,2),
    active NUMBER(1) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT pk_budgets PRIMARY KEY (id),
    CONSTRAINT fk_budgets_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_budgets_category FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT uq_budgets_user_category_month UNIQUE (user_id, category_id, budget_month)
);

CREATE INDEX idx_budgets_user ON budgets (user_id);
CREATE INDEX idx_budgets_user_active ON budgets (user_id, active);
CREATE INDEX idx_budgets_category ON budgets (category_id);
