CREATE TABLE goals (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id NUMBER(19) NOT NULL,
    name VARCHAR2(255) NOT NULL,
    target_amount NUMBER(19,2) NOT NULL,
    deadline DATE NOT NULL,
    completed NUMBER(1) NOT NULL,
    active NUMBER(1) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT pk_goals PRIMARY KEY (id),
    CONSTRAINT fk_goals_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_goals_user ON goals (user_id);
CREATE INDEX idx_goals_user_active ON goals (user_id, active);
