CREATE TABLE goal_contributions (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    goal_id NUMBER(19) NOT NULL,
    amount NUMBER(19,2) NOT NULL,
    contribution_date DATE NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT pk_goal_contributions PRIMARY KEY (id),
    CONSTRAINT fk_goal_contributions_goal FOREIGN KEY (goal_id) REFERENCES goals (id)
);

CREATE INDEX idx_goal_contributions_goal ON goal_contributions (goal_id);
