CREATE TABLE planning_entries (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id NUMBER(19) NOT NULL,
    account_id NUMBER(19) NOT NULL,
    category_id NUMBER(19),
    type VARCHAR(20) NOT NULL,
    amount NUMBER(19,2) NOT NULL,
    description VARCHAR(255) NOT NULL,
    due_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL,
    settled_at TIMESTAMP,
    transaction_id NUMBER(19),
    active NUMBER(1) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT pk_planning_entries PRIMARY KEY (id),
    CONSTRAINT fk_planning_entries_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_planning_entries_account FOREIGN KEY (account_id) REFERENCES accounts (id),
    CONSTRAINT fk_planning_entries_category FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT fk_planning_entries_transaction FOREIGN KEY (transaction_id) REFERENCES transactions (id)
);

CREATE INDEX idx_planning_entries_user_due_date ON planning_entries (user_id, due_date);
CREATE INDEX idx_planning_entries_user_status ON planning_entries (user_id, status);
