CREATE TABLE investment_assets (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id NUMBER(19) NOT NULL,
    account_id NUMBER(19),
    name VARCHAR2(255) NOT NULL,
    ticker VARCHAR2(32),
    type VARCHAR2(32) NOT NULL,
    active NUMBER(1) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT pk_investment_assets PRIMARY KEY (id),
    CONSTRAINT fk_investment_assets_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_investment_assets_account FOREIGN KEY (account_id) REFERENCES accounts (id)
);

CREATE INDEX idx_investment_assets_user ON investment_assets (user_id);
CREATE INDEX idx_investment_assets_user_active ON investment_assets (user_id, active);
