CREATE TABLE investment_operations (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    asset_id NUMBER(19) NOT NULL,
    type VARCHAR2(16) NOT NULL,
    quantity NUMBER(19,8) NOT NULL,
    unit_price NUMBER(19,2) NOT NULL,
    operation_date DATE NOT NULL,
    active NUMBER(1) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT pk_investment_operations PRIMARY KEY (id),
    CONSTRAINT fk_investment_operations_asset FOREIGN KEY (asset_id) REFERENCES investment_assets (id)
);

CREATE INDEX idx_investment_operations_asset_date ON investment_operations (asset_id, operation_date);
CREATE INDEX idx_investment_operations_asset_active ON investment_operations (asset_id, active);
