CREATE TABLE users (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email VARCHAR2(255) NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE UNIQUE INDEX uq_users_email ON users (email);
