CREATE TABLE investment_valuations (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    asset_id NUMBER(19) NOT NULL,
    value_date DATE NOT NULL,
    total_value NUMBER(19,2) NOT NULL,
    active NUMBER(1) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT pk_investment_valuations PRIMARY KEY (id),
    CONSTRAINT fk_investment_valuations_asset FOREIGN KEY (asset_id) REFERENCES investment_assets (id)
);

CREATE INDEX idx_investment_valuations_asset_date ON investment_valuations (asset_id, value_date);
CREATE INDEX idx_investment_valuations_asset_active ON investment_valuations (asset_id, active);
