CREATE TABLE user_preferences (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id NUMBER(19) NOT NULL,
    currency VARCHAR2(8) NOT NULL,
    date_format VARCHAR2(16) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT pk_user_preferences PRIMARY KEY (id),
    CONSTRAINT fk_user_preferences_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uq_user_preferences_user UNIQUE (user_id)
);
