CREATE TABLE login_history (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id NUMBER(19),
    email_attempted VARCHAR2(255) NOT NULL,
    ip_address VARCHAR2(64),
    success NUMBER(1) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT pk_login_history PRIMARY KEY (id),
    CONSTRAINT fk_login_history_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_login_history_user_created ON login_history (user_id, created_at);
