CREATE TABLE accounts (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id NUMBER(19) NOT NULL,
    name VARCHAR2(255) NOT NULL,
    icon VARCHAR2(64) NOT NULL,
    color VARCHAR2(16) NOT NULL,
    type VARCHAR2(32) NOT NULL,
    balance NUMBER(19,2) NOT NULL,
    credit_limit NUMBER(19,2),
    current_invoice NUMBER(19,2),
    active NUMBER(1) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT pk_accounts PRIMARY KEY (id),
    CONSTRAINT fk_accounts_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_accounts_user ON accounts (user_id);
CREATE INDEX idx_accounts_user_active ON accounts (user_id, active);
