CREATE TABLE account_transfers (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id NUMBER(19) NOT NULL,
    source_account_id NUMBER(19) NOT NULL,
    destination_account_id NUMBER(19) NOT NULL,
    amount NUMBER(19,2) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT pk_account_transfers PRIMARY KEY (id),
    CONSTRAINT fk_account_transfers_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_account_transfers_source FOREIGN KEY (source_account_id) REFERENCES accounts (id),
    CONSTRAINT fk_account_transfers_destination FOREIGN KEY (destination_account_id) REFERENCES accounts (id)
);

CREATE INDEX idx_account_transfers_source ON account_transfers (source_account_id);
CREATE INDEX idx_account_transfers_destination ON account_transfers (destination_account_id);
