CREATE TABLE categories (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id NUMBER(19) NOT NULL,
    parent_category_id NUMBER(19),
    name VARCHAR2(255) NOT NULL,
    icon VARCHAR2(64) NOT NULL,
    color VARCHAR2(16) NOT NULL,
    is_default NUMBER(1) NOT NULL,
    active NUMBER(1) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT pk_categories PRIMARY KEY (id),
    CONSTRAINT fk_categories_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_categories_parent FOREIGN KEY (parent_category_id) REFERENCES categories (id)
);

CREATE INDEX idx_categories_user ON categories (user_id);
CREATE INDEX idx_categories_user_active ON categories (user_id, active);
CREATE INDEX idx_categories_parent ON categories (parent_category_id);
