CREATE TABLE category_keywords (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id NUMBER(19) NOT NULL,
    category_id NUMBER(19) NOT NULL,
    keyword VARCHAR2(255) NOT NULL,
    keyword_normalized VARCHAR2(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT pk_category_keywords PRIMARY KEY (id),
    CONSTRAINT fk_category_keywords_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_category_keywords_category FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT uq_category_keywords_user_keyword UNIQUE (user_id, keyword_normalized)
);

CREATE INDEX idx_category_keywords_category ON category_keywords (category_id);
CREATE INDEX idx_category_keywords_user ON category_keywords (user_id);
