CREATE TABLE default_categories (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR2(255) NOT NULL,
    icon VARCHAR2(64) NOT NULL,
    color VARCHAR2(16) NOT NULL,
    active NUMBER(1) NOT NULL,
    sort_order NUMBER(10) NOT NULL,
    CONSTRAINT pk_default_categories PRIMARY KEY (id)
);

CREATE INDEX idx_default_categories_active_sort ON default_categories (active, sort_order);

INSERT INTO default_categories (name, icon, color, active, sort_order) VALUES ('Alimentação', 'utensils', '#f97316', 1, 1);
INSERT INTO default_categories (name, icon, color, active, sort_order) VALUES ('Transporte', 'car', '#3b82f6', 1, 2);
INSERT INTO default_categories (name, icon, color, active, sort_order) VALUES ('Moradia', 'home', '#22c55e', 1, 3);
INSERT INTO default_categories (name, icon, color, active, sort_order) VALUES ('Lazer', 'party-popper', '#a855f7', 1, 4);
INSERT INTO default_categories (name, icon, color, active, sort_order) VALUES ('Saúde', 'heart-pulse', '#ef4444', 1, 5);
