CREATE TABLE transactions (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id NUMBER(19) NOT NULL,
    account_id NUMBER(19) NOT NULL,
    category_id NUMBER(19),
    type VARCHAR2(16) NOT NULL,
    amount NUMBER(19,2) NOT NULL,
    description VARCHAR2(255) NOT NULL,
    transaction_date DATE NOT NULL,
    note VARCHAR2(1000),
    active NUMBER(1) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT pk_transactions PRIMARY KEY (id),
    CONSTRAINT fk_transactions_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_transactions_account FOREIGN KEY (account_id) REFERENCES accounts (id),
    CONSTRAINT fk_transactions_category FOREIGN KEY (category_id) REFERENCES categories (id)
);

CREATE INDEX idx_transactions_user ON transactions (user_id);
CREATE INDEX idx_transactions_user_active ON transactions (user_id, active);
CREATE INDEX idx_transactions_account ON transactions (account_id);
CREATE INDEX idx_transactions_category ON transactions (category_id);
CREATE INDEX idx_transactions_date ON transactions (transaction_date);
